#: kivy 1.0.9

<HikingApp>:
    canvas:
        Rectangle:
            pos: self.centre_x -5,0
            size:10, self.height

<TabBar>:
    do_default_tab: False
    tab_width: self.width / 5  

    TabbedPanelItem:
        text: 'Home'
        Home:

    TabbedPanelItem:
        text: 'Add Climb'
        AddClimbs:       

    TabbedPanelItem:
        text: 'Mountains'
        Mountains:

    TabbedPanelItem:
        text: 'Climbs'
        on_release: climbs.show_climbs()
        Climbs:
            id: climbs

    TabbedPanelItem:
        text: 'Statistics'
        on_release: statistics.show_statistics()
        Statistics:
            id: statistics


<Climbs>:
    orientation: "vertical"

    TextInput:
        id: climb_search
        size_hint_y: None
        height: dp(45)
        font_size: sp(16)
        hint_text: "Search climbs..."
        multiline: False
        on_text: root.show_climbs()

    BoxLayout:
        id: classification_filters
        orientation: "vertical"
        size_hint_y: None
        height: self.minimum_height

    ScrollView:
        do_scroll_x: False
        BoxLayout:
            id: climb_list
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height

    BoxLayout:
        id: sort_date
        orientation: "horizontal"
        size_hint_y: None
        height: dp(50)

        Button:
            text: "Date Des."
            on_release: root.sort_climbs("date", True)

        Button:
            text: "Date Asc."
            on_release: root.sort_climbs("date", False)


<AddClimbs>:
    BoxLayout:
        orientation: "vertical"

        TextInput:
            id: mountain_search
            hint_text: "Search for a mountain"
            on_text: root.search_mountains(self.text)

        BoxLayout:
            id: mountain_results
            orientation: "vertical"

        Label:
            id: selected_mountain
            text: "No mountain selected"

        TextInput:
            id: date_climbed
            hint_text: "Date climbed"

        TextInput:
            id: time_climbed
            hint_text: "Time climbed"

        Button:
            text: "Add Climb"
            on_release: root.add_climb_from_form()

<Mountains>:
    orientation: "vertical"

    BoxLayout:
        id: classification_filters
        orientation: "vertical"
        size_hint_y: None
        height: self.minimum_height


    ScrollView:
        do_scroll_x: False

        BoxLayout:
            id: mountain_list
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height

    BoxLayout:
        id: sorting_filters
        orientation: "horizontal"
        size_hint_y: None
        height: dp(50)
        Button:
            text: "Height Des."
            on_release: root.sort_mountains("height", True)

        Button:
            text: "Height Asc."
            on_release: root.sort_mountains("height", False)

        Button:
            text: "A–Z"
            on_release: root.sort_mountains("name", False)

        Button:
            text: "Z–A"
            on_release: root.sort_mountains("name", True)

<Statistics>:
    orientation: "vertical"

    Label:
        text: "Your Climbing Statistics"
        font_size: sp(24)
        size_hint_y: None
        height: dp(50)

    BoxLayout:
        id: statistic_table
        orientation: "vertical"
        size_hint_y: None
        height: self.minimum_height

    Widget:
        size_hint_y: 1




